-- =========================================================
-- NEXORA
-- Migration: 001_create_security_tables.sql
-- Purpose: Create users, roles, and user_roles tables
-- Database: PostgreSQL
-- =========================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS procurement;

SET search_path TO procurement, public;

-- ---------------------------------------------------------
-- USERS
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    first_name VARCHAR(100) NOT NULL,

    last_name VARCHAR(100) NOT NULL,

    email VARCHAR(255) NOT NULL,

    password_hash VARCHAR(255) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    last_login_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_email
        UNIQUE (email),

    CONSTRAINT chk_users_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE',
                'LOCKED'
            )
        ),

    CONSTRAINT chk_users_email_lowercase
        CHECK (
            email = LOWER(email)
        )
);

CREATE INDEX IF NOT EXISTS idx_users_status
    ON users (status);

CREATE INDEX IF NOT EXISTS idx_users_name
    ON users (
        last_name,
        first_name
    );

-- ---------------------------------------------------------
-- ROLES
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    role_code VARCHAR(50) NOT NULL,

    role_name VARCHAR(100) NOT NULL,

    description TEXT,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_roles_role_code
        UNIQUE (role_code),

    CONSTRAINT uq_roles_role_name
        UNIQUE (role_name)
);

CREATE INDEX IF NOT EXISTS idx_roles_active
    ON roles (active);

-- ---------------------------------------------------------
-- USER ROLES
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_roles (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    role_id BIGINT NOT NULL,

    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    assigned_by BIGINT,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_user_roles_assigned_by
        FOREIGN KEY (assigned_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id
    ON user_roles (user_id);

CREATE INDEX IF NOT EXISTS idx_user_roles_role_id
    ON user_roles (role_id);

CREATE INDEX IF NOT EXISTS idx_user_roles_active
    ON user_roles (active);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_roles_active_assignment
    ON user_roles (
        user_id,
        role_id
    )
    WHERE active = TRUE;

-- ---------------------------------------------------------
-- INITIAL ROLES
-- ---------------------------------------------------------

INSERT INTO roles (
    role_code,
    role_name,
    description
)
VALUES
    (
        'REQUESTER',
        'Requesting Employee',
        'Creates and submits purchase requisitions.'
    ),
    (
        'PROCUREMENT_OFFICER',
        'Procurement Officer',
        'Manages suppliers and creates purchase orders.'
    ),
    (
        'NOMINATED_APPROVER',
        'Nominated Approver',
        'Reviews and approves procurement documents.'
    ),
    (
        'PROCUREMENT_MANAGER',
        'Procurement Manager',
        'Oversees procurement operations and approval configuration.'
    ),
    (
        'SYSTEM_ADMINISTRATOR',
        'System Administrator',
        'Manages users, roles, security, and system configuration.'
    )
ON CONFLICT (role_code)
DO NOTHING;

COMMIT;