-- =========================================================
-- NEXORA
-- Migration: 002_create_supplier_tables.sql
-- Purpose: Create suppliers and supplier_contacts tables
-- Database: PostgreSQL
-- =========================================================

BEGIN;

SET search_path TO procurement, public;

-- =========================================================
-- SUPPLIERS
-- =========================================================

CREATE TABLE IF NOT EXISTS suppliers (

    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    supplier_code VARCHAR(30) NOT NULL,

    supplier_name VARCHAR(200) NOT NULL,

    email VARCHAR(255),

    phone VARCHAR(50),

    address_line_1 VARCHAR(200),

    address_line_2 VARCHAR(200),

    city VARCHAR(100),

    state_region VARCHAR(100),

    postal_code VARCHAR(20),

    country_code VARCHAR(3),

    tax_registration_number VARCHAR(50),

    payment_terms VARCHAR(100),

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_by BIGINT NOT NULL,

    CONSTRAINT uq_supplier_code
        UNIQUE (supplier_code),

    CONSTRAINT chk_supplier_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE',
                'ON_HOLD'
            )
        ),

    CONSTRAINT fk_supplier_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT

);

CREATE INDEX idx_supplier_name
ON suppliers(supplier_name);

CREATE INDEX idx_supplier_status
ON suppliers(status);

CREATE INDEX idx_supplier_tax
ON suppliers(tax_registration_number);


-- =========================================================
-- SUPPLIER CONTACTS
-- =========================================================

CREATE TABLE IF NOT EXISTS supplier_contacts (

    supplier_contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    supplier_id BIGINT NOT NULL,

    contact_name VARCHAR(150) NOT NULL,

    job_title VARCHAR(100),

    email VARCHAR(255),

    phone VARCHAR(50),

    primary_contact BOOLEAN NOT NULL DEFAULT FALSE,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_by BIGINT NOT NULL,

    CONSTRAINT fk_supplier_contact_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_contact_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_contact_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT

);

CREATE INDEX idx_supplier_contact_supplier
ON supplier_contacts(supplier_id);

CREATE INDEX idx_supplier_contact_email
ON supplier_contacts(email);

CREATE INDEX idx_supplier_contact_active
ON supplier_contacts(active);

CREATE UNIQUE INDEX uq_supplier_primary_contact
ON supplier_contacts(supplier_id)
WHERE
    primary_contact = TRUE
    AND active = TRUE;

COMMIT;
