-- =========================================================
-- NEXORA
-- Migration: 003_create_catalogue_tables.sql
-- Purpose: Create catalogue and supplier-item tables
-- Database: PostgreSQL
-- =========================================================

BEGIN;

SET search_path TO procurement, public;

-- =========================================================
-- ITEM CATEGORIES
-- =========================================================

CREATE TABLE IF NOT EXISTS item_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(50) NOT NULL,
    category_name VARCHAR(150) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_item_categories_code UNIQUE (category_code),
    CONSTRAINT uq_item_categories_name UNIQUE (category_name)
);

CREATE INDEX IF NOT EXISTS idx_item_categories_active
    ON item_categories (active);


-- =========================================================
-- UNITS OF MEASURE
-- =========================================================

CREATE TABLE IF NOT EXISTS units_of_measure (
    uom_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uom_code VARCHAR(20) NOT NULL,
    uom_name VARCHAR(100) NOT NULL,
    uom_type VARCHAR(30),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_units_of_measure_code UNIQUE (uom_code),
    CONSTRAINT uq_units_of_measure_name UNIQUE (uom_name),

    CONSTRAINT chk_units_of_measure_type
        CHECK (
            uom_type IS NULL
            OR uom_type IN ('WEIGHT', 'VOLUME', 'COUNT', 'PACKAGING')
        )
);

CREATE INDEX IF NOT EXISTS idx_units_of_measure_active
    ON units_of_measure (active);

CREATE INDEX IF NOT EXISTS idx_units_of_measure_type
    ON units_of_measure (uom_type);


-- =========================================================
-- CATALOGUE ITEMS
-- =========================================================

CREATE TABLE IF NOT EXISTS catalogue_items (
    catalogue_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR(50) NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    item_type VARCHAR(40) NOT NULL,
    category_id BIGINT NOT NULL,
    purchase_uom_id BIGINT NOT NULL,
    stock_uom_id BIGINT,
    conversion_factor NUMERIC(18,4),
    shelf_life_days INTEGER,
    storage_condition VARCHAR(200),
    batch_tracking_required BOOLEAN NOT NULL DEFAULT FALSE,
    expiry_tracking_required BOOLEAN NOT NULL DEFAULT FALSE,
    allergen_information TEXT,
    country_of_origin VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,

    CONSTRAINT uq_catalogue_items_code UNIQUE (item_code),

    CONSTRAINT fk_catalogue_items_category
        FOREIGN KEY (category_id)
        REFERENCES item_categories (category_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_catalogue_items_purchase_uom
        FOREIGN KEY (purchase_uom_id)
        REFERENCES units_of_measure (uom_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_catalogue_items_stock_uom
        FOREIGN KEY (stock_uom_id)
        REFERENCES units_of_measure (uom_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_catalogue_items_created_by
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_catalogue_items_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_catalogue_items_type
        CHECK (
            item_type IN (
                'RAW_MATERIAL',
                'INGREDIENT',
                'PACKAGING_MATERIAL',
                'CLEANING_MATERIAL',
                'MAINTENANCE_ITEM',
                'NON_STOCK_ITEM',
                'SERVICE'
            )
        ),

    CONSTRAINT chk_catalogue_items_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    CONSTRAINT chk_catalogue_items_conversion_factor
        CHECK (
            conversion_factor IS NULL
            OR conversion_factor > 0
        ),

    CONSTRAINT chk_catalogue_items_shelf_life
        CHECK (
            shelf_life_days IS NULL
            OR shelf_life_days >= 0
        )
);

CREATE INDEX IF NOT EXISTS idx_catalogue_items_name
    ON catalogue_items (item_name);

CREATE INDEX IF NOT EXISTS idx_catalogue_items_type
    ON catalogue_items (item_type);

CREATE INDEX IF NOT EXISTS idx_catalogue_items_category
    ON catalogue_items (category_id);

CREATE INDEX IF NOT EXISTS idx_catalogue_items_status
    ON catalogue_items (status);

CREATE INDEX IF NOT EXISTS idx_catalogue_items_batch_tracking
    ON catalogue_items (batch_tracking_required);

CREATE INDEX IF NOT EXISTS idx_catalogue_items_expiry_tracking
    ON catalogue_items (expiry_tracking_required);


-- =========================================================
-- SUPPLIER ITEMS
-- =========================================================

CREATE TABLE IF NOT EXISTS supplier_items (
    supplier_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    catalogue_item_id BIGINT NOT NULL,
    supplier_item_code VARCHAR(100),
    purchase_uom_id BIGINT NOT NULL,
    unit_price NUMERIC(18,2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL DEFAULT 'AUD',
    minimum_order_quantity NUMERIC(18,4),
    lead_time_days INTEGER,
    preferred_supplier BOOLEAN NOT NULL DEFAULT FALSE,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,

    CONSTRAINT fk_supplier_items_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers (supplier_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_items_catalogue_item
        FOREIGN KEY (catalogue_item_id)
        REFERENCES catalogue_items (catalogue_item_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_items_purchase_uom
        FOREIGN KEY (purchase_uom_id)
        REFERENCES units_of_measure (uom_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_items_created_by
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_items_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_supplier_items_unit_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_supplier_items_minimum_order_quantity
        CHECK (
            minimum_order_quantity IS NULL
            OR minimum_order_quantity > 0
        ),

    CONSTRAINT chk_supplier_items_lead_time
        CHECK (
            lead_time_days IS NULL
            OR lead_time_days >= 0
        ),

    CONSTRAINT chk_supplier_items_effective_dates
        CHECK (
            effective_to IS NULL
            OR effective_to >= effective_from
        )
);

CREATE INDEX IF NOT EXISTS idx_supplier_items_supplier
    ON supplier_items (supplier_id);

CREATE INDEX IF NOT EXISTS idx_supplier_items_catalogue_item
    ON supplier_items (catalogue_item_id);

CREATE INDEX IF NOT EXISTS idx_supplier_items_supplier_code
    ON supplier_items (supplier_item_code);

CREATE INDEX IF NOT EXISTS idx_supplier_items_active
    ON supplier_items (active);

CREATE INDEX IF NOT EXISTS idx_supplier_items_preferred
    ON supplier_items (preferred_supplier);

CREATE INDEX IF NOT EXISTS idx_supplier_items_lookup
    ON supplier_items (
        supplier_id,
        catalogue_item_id,
        effective_from
    );

CREATE UNIQUE INDEX IF NOT EXISTS uq_supplier_items_active_preferred
    ON supplier_items (catalogue_item_id)
    WHERE preferred_supplier = TRUE
      AND active = TRUE
      AND effective_to IS NULL;

COMMIT;
