-- =========================================================
-- NEXORA
-- Migration: 004_create_requisition_tables.sql
-- Purpose: Create purchase requisition tables
-- Database: PostgreSQL
-- =========================================================

BEGIN;

SET search_path TO procurement, public;

-- =========================================================
-- PURCHASE REQUISITIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS purchase_requisitions (
    purchase_requisition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_number VARCHAR(30) NOT NULL,
    requested_by BIGINT NOT NULL,
    department VARCHAR(100) NOT NULL,
    required_date DATE NOT NULL,
    justification TEXT NOT NULL,
    estimated_total NUMERIC(18,2) NOT NULL DEFAULT 0.00,
    currency_code VARCHAR(3) NOT NULL DEFAULT 'AUD',
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    submitted_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,

    CONSTRAINT uq_purchase_requisitions_number
        UNIQUE (requisition_number),

    CONSTRAINT fk_purchase_requisitions_requested_by
        FOREIGN KEY (requested_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_purchase_requisitions_created_by
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_purchase_requisitions_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_purchase_requisitions_total
        CHECK (estimated_total >= 0),

    CONSTRAINT chk_purchase_requisitions_status
        CHECK (
            status IN (
                'DRAFT',
                'SUBMITTED',
                'PENDING_APPROVAL',
                'RETURNED_FOR_AMENDMENT',
                'APPROVED',
                'REJECTED',
                'CANCELLED',
                'PARTIALLY_CONVERTED',
                'CONVERTED_TO_PO',
                'CLOSED'
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_purchase_requisitions_requested_by
    ON purchase_requisitions (requested_by);

CREATE INDEX IF NOT EXISTS idx_purchase_requisitions_department
    ON purchase_requisitions (department);

CREATE INDEX IF NOT EXISTS idx_purchase_requisitions_status
    ON purchase_requisitions (status);

CREATE INDEX IF NOT EXISTS idx_purchase_requisitions_required_date
    ON purchase_requisitions (required_date);

CREATE INDEX IF NOT EXISTS idx_purchase_requisitions_created_at
    ON purchase_requisitions (created_at);


-- =========================================================
-- PURCHASE REQUISITION ITEMS
-- =========================================================

CREATE TABLE IF NOT EXISTS purchase_requisition_items (
    purchase_requisition_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_requisition_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    catalogue_item_id BIGINT,
    description VARCHAR(500) NOT NULL,
    quantity NUMERIC(18,4) NOT NULL,
    requested_uom_id BIGINT NOT NULL,
    estimated_unit_price NUMERIC(18,2) NOT NULL DEFAULT 0.00,
    estimated_line_total NUMERIC(18,2) NOT NULL DEFAULT 0.00,
    required_date DATE,
    non_catalogue_item BOOLEAN NOT NULL DEFAULT FALSE,
    converted_quantity NUMERIC(18,4) NOT NULL DEFAULT 0.0000,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,

    CONSTRAINT fk_purchase_requisition_items_requisition
        FOREIGN KEY (purchase_requisition_id)
        REFERENCES purchase_requisitions (purchase_requisition_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_purchase_requisition_items_catalogue_item
        FOREIGN KEY (catalogue_item_id)
        REFERENCES catalogue_items (catalogue_item_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_purchase_requisition_items_uom
        FOREIGN KEY (requested_uom_id)
        REFERENCES units_of_measure (uom_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_purchase_requisition_items_created_by
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_purchase_requisition_items_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_purchase_requisition_items_line
        UNIQUE (purchase_requisition_id, line_number),

    CONSTRAINT chk_purchase_requisition_items_line_number
        CHECK (line_number > 0),

    CONSTRAINT chk_purchase_requisition_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_purchase_requisition_items_unit_price
        CHECK (estimated_unit_price >= 0),

    CONSTRAINT chk_purchase_requisition_items_line_total
        CHECK (estimated_line_total >= 0),

    CONSTRAINT chk_purchase_requisition_items_converted_quantity
        CHECK (
            converted_quantity >= 0
            AND converted_quantity <= quantity
        ),

    CONSTRAINT chk_purchase_requisition_items_catalogue_reference
        CHECK (
            (non_catalogue_item = FALSE AND catalogue_item_id IS NOT NULL)
            OR
            (non_catalogue_item = TRUE)
        )
);

CREATE INDEX IF NOT EXISTS idx_purchase_requisition_items_requisition
    ON purchase_requisition_items (purchase_requisition_id);

CREATE INDEX IF NOT EXISTS idx_purchase_requisition_items_catalogue_item
    ON purchase_requisition_items (catalogue_item_id);

CREATE INDEX IF NOT EXISTS idx_purchase_requisition_items_required_date
    ON purchase_requisition_items (required_date);

CREATE INDEX IF NOT EXISTS idx_purchase_requisition_items_non_catalogue
    ON purchase_requisition_items (non_catalogue_item);

COMMIT;
