-- =========================================================
-- NEXORA
-- Migration: 005_create_purchase_order_tables.sql
-- Purpose: Create Purchase Order tables
-- Database: PostgreSQL
-- =========================================================

BEGIN;

SET search_path TO procurement, public;

-- =========================================================
-- PURCHASE ORDERS
-- =========================================================

CREATE TABLE IF NOT EXISTS purchase_orders (

    purchase_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    po_number VARCHAR(30) NOT NULL,

    order_type VARCHAR(20) NOT NULL DEFAULT 'STANDARD',

    source_requisition_id BIGINT,

    supplier_id BIGINT NOT NULL,

    supplier_contact_id BIGINT,

    order_date DATE NOT NULL DEFAULT CURRENT_DATE,

    required_delivery_date DATE,

    delivery_address TEXT NOT NULL,

    currency_code VARCHAR(3) NOT NULL DEFAULT 'AUD',

    subtotal NUMERIC(18,2) NOT NULL DEFAULT 0,

    tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0,

    total_amount NUMERIC(18,2) NOT NULL DEFAULT 0,

    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',

    revision_number INTEGER NOT NULL DEFAULT 0,

    direct_purchase_reason TEXT,

    approval_threshold_applied NUMERIC(18,2),

    submitted_at TIMESTAMPTZ,

    approved_at TIMESTAMPTZ,

    sent_at TIMESTAMPTZ,

    cancelled_at TIMESTAMPTZ,

    closed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_by BIGINT NOT NULL,

    CONSTRAINT uq_purchase_orders_number
        UNIQUE(po_number),

    CONSTRAINT fk_po_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id),

    CONSTRAINT fk_po_supplier_contact
        FOREIGN KEY (supplier_contact_id)
        REFERENCES supplier_contacts(supplier_contact_id),

    CONSTRAINT fk_po_requisition
        FOREIGN KEY (source_requisition_id)
        REFERENCES purchase_requisitions(purchase_requisition_id),

    CONSTRAINT fk_po_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

    CONSTRAINT fk_po_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id),

    CONSTRAINT chk_po_order_type
        CHECK (
            order_type IN
            (
                'STANDARD',
                'DIRECT'
            )
        ),

    CONSTRAINT chk_po_total
        CHECK(total_amount >= 0),

    CONSTRAINT chk_po_status
        CHECK(
            status IN
            (
                'DRAFT',
                'SUBMITTED',
                'PENDING_APPROVAL',
                'RETURNED_FOR_AMENDMENT',
                'APPROVED',
                'REJECTED',
                'ON_HOLD',
                'CANCELLED',
                'SENT_TO_SUPPLIER',
                'PARTIALLY_RECEIVED',
                'FULLY_RECEIVED',
                'PARTIALLY_INVOICED',
                'FULLY_INVOICED',
                'MATCHING_EXCEPTION',
                'MATCHED',
                'CLOSED'
            )
        )

);

CREATE INDEX idx_po_supplier
ON purchase_orders(supplier_id);

CREATE INDEX idx_po_status
ON purchase_orders(status);

CREATE INDEX idx_po_order_date
ON purchase_orders(order_date);

CREATE INDEX idx_po_requisition
ON purchase_orders(source_requisition_id);

CREATE INDEX idx_po_created_by
ON purchase_orders(created_by);

CREATE INDEX idx_po_supplier_status
ON purchase_orders(supplier_id,status);

-- =========================================================
-- PURCHASE ORDER ITEMS
-- =========================================================

CREATE TABLE IF NOT EXISTS purchase_order_items (

    purchase_order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    purchase_order_id BIGINT NOT NULL,

    line_number INTEGER NOT NULL,

    source_requisition_item_id BIGINT,

    catalogue_item_id BIGINT,

    supplier_item_id BIGINT,

    description VARCHAR(500) NOT NULL,

    quantity NUMERIC(18,4) NOT NULL,

    ordered_uom_id BIGINT NOT NULL,

    unit_price NUMERIC(18,2) NOT NULL,

    tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,

    tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0,

    line_total NUMERIC(18,2) NOT NULL DEFAULT 0,

    required_delivery_date DATE,

    price_overridden BOOLEAN NOT NULL DEFAULT FALSE,

    price_override_reason TEXT,

    non_catalogue_item BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_by BIGINT NOT NULL,

    CONSTRAINT fk_po_item_po
        FOREIGN KEY (purchase_order_id)
        REFERENCES purchase_orders(purchase_order_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_po_item_catalogue
        FOREIGN KEY (catalogue_item_id)
        REFERENCES catalogue_items(catalogue_item_id),

    CONSTRAINT fk_po_item_supplier_item
        FOREIGN KEY (supplier_item_id)
        REFERENCES supplier_items(supplier_item_id),

    CONSTRAINT fk_po_item_req_item
        FOREIGN KEY (source_requisition_item_id)
        REFERENCES purchase_requisition_items(purchase_requisition_item_id),

    CONSTRAINT fk_po_item_uom
        FOREIGN KEY (ordered_uom_id)
        REFERENCES units_of_measure(uom_id),

    CONSTRAINT fk_po_item_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

    CONSTRAINT fk_po_item_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id),

    CONSTRAINT uq_po_line
        UNIQUE(purchase_order_id,line_number),

    CONSTRAINT chk_po_item_quantity
        CHECK(quantity > 0),

    CONSTRAINT chk_po_item_price
        CHECK(unit_price >= 0),

    CONSTRAINT chk_po_item_tax
        CHECK(tax_rate >= 0),

    CONSTRAINT chk_po_item_total
        CHECK(line_total >= 0)

);

CREATE INDEX idx_po_item_po
ON purchase_order_items(purchase_order_id);

CREATE INDEX idx_po_item_catalogue
ON purchase_order_items(catalogue_item_id);

CREATE INDEX idx_po_item_supplier
ON purchase_order_items(supplier_item_id);

COMMIT;
