-- =========================================================
-- NEXORA
-- Migration: 006_create_workflow_tables.sql
-- Purpose: Create approval, status history, notification,
--          and audit tables
-- Database: PostgreSQL
-- =========================================================

BEGIN;

SET search_path TO procurement, public;

-- =========================================================
-- APPROVAL RULES
-- =========================================================

CREATE TABLE IF NOT EXISTS approval_rules (
    approval_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    document_type VARCHAR(30) NOT NULL,

    minimum_amount NUMERIC(18,2) NOT NULL DEFAULT 0.00,

    maximum_amount NUMERIC(18,2),

    currency_code VARCHAR(3) NOT NULL DEFAULT 'AUD',

    approval_level INTEGER NOT NULL DEFAULT 1,

    approver_user_id BIGINT,

    approver_role_id BIGINT,

    auto_approve BOOLEAN NOT NULL DEFAULT FALSE,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,

    effective_to DATE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_by BIGINT NOT NULL,

    CONSTRAINT fk_approval_rules_approver_user
        FOREIGN KEY (approver_user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_approval_rules_approver_role
        FOREIGN KEY (approver_role_id)
        REFERENCES roles (role_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_approval_rules_created_by
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_approval_rules_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_approval_rules_document_type
        CHECK (
            document_type IN (
                'PURCHASE_REQUISITION',
                'PURCHASE_ORDER'
            )
        ),

    CONSTRAINT chk_approval_rules_minimum_amount
        CHECK (minimum_amount >= 0),

    CONSTRAINT chk_approval_rules_maximum_amount
        CHECK (
            maximum_amount IS NULL
            OR maximum_amount >= minimum_amount
        ),

    CONSTRAINT chk_approval_rules_level
        CHECK (approval_level > 0),

    CONSTRAINT chk_approval_rules_effective_dates
        CHECK (
            effective_to IS NULL
            OR effective_to >= effective_from
        ),

    CONSTRAINT chk_approval_rules_approver
        CHECK (
            (
                auto_approve = TRUE
                AND approver_user_id IS NULL
                AND approver_role_id IS NULL
            )
            OR
            (
                auto_approve = FALSE
                AND (
                    approver_user_id IS NOT NULL
                    OR approver_role_id IS NOT NULL
                )
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_approval_rules_document_type
    ON approval_rules (document_type);

CREATE INDEX IF NOT EXISTS idx_approval_rules_active
    ON approval_rules (active);

CREATE INDEX IF NOT EXISTS idx_approval_rules_approver_user
    ON approval_rules (approver_user_id);

CREATE INDEX IF NOT EXISTS idx_approval_rules_approver_role
    ON approval_rules (approver_role_id);

CREATE INDEX IF NOT EXISTS idx_approval_rules_effective_dates
    ON approval_rules (effective_from, effective_to);

CREATE INDEX IF NOT EXISTS idx_approval_rules_amount_lookup
    ON approval_rules (
        document_type,
        currency_code,
        minimum_amount,
        maximum_amount
    );


-- =========================================================
-- PURCHASE REQUISITION APPROVALS
-- =========================================================

CREATE TABLE IF NOT EXISTS purchase_requisition_approvals (
    purchase_requisition_approval_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    purchase_requisition_id BIGINT NOT NULL,

    approval_rule_id BIGINT,

    approval_level INTEGER NOT NULL DEFAULT 1,

    approver_id BIGINT,

    decision VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    comments TEXT,

    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    decided_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pr_approvals_requisition
        FOREIGN KEY (purchase_requisition_id)
        REFERENCES purchase_requisitions (purchase_requisition_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_pr_approvals_rule
        FOREIGN KEY (approval_rule_id)
        REFERENCES approval_rules (approval_rule_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_pr_approvals_approver
        FOREIGN KEY (approver_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_pr_approvals_level
        CHECK (approval_level > 0),

    CONSTRAINT chk_pr_approvals_decision
        CHECK (
            decision IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'RETURNED_FOR_AMENDMENT',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_pr_approvals_comments
        CHECK (
            decision NOT IN (
                'REJECTED',
                'RETURNED_FOR_AMENDMENT'
            )
            OR NULLIF(BTRIM(comments), '') IS NOT NULL
        ),

    CONSTRAINT chk_pr_approvals_decided_at
        CHECK (
            (decision = 'PENDING' AND decided_at IS NULL)
            OR
            (decision <> 'PENDING' AND decided_at IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_pr_approvals_requisition
    ON purchase_requisition_approvals (purchase_requisition_id);

CREATE INDEX IF NOT EXISTS idx_pr_approvals_approver
    ON purchase_requisition_approvals (approver_id);

CREATE INDEX IF NOT EXISTS idx_pr_approvals_decision
    ON purchase_requisition_approvals (decision);

CREATE INDEX IF NOT EXISTS idx_pr_approvals_level
    ON purchase_requisition_approvals (
        purchase_requisition_id,
        approval_level
    );

CREATE UNIQUE INDEX IF NOT EXISTS uq_pr_approvals_pending_level
    ON purchase_requisition_approvals (
        purchase_requisition_id,
        approval_level
    )
    WHERE decision = 'PENDING';


-- =========================================================
-- PURCHASE ORDER APPROVALS
-- =========================================================

CREATE TABLE IF NOT EXISTS purchase_order_approvals (
    purchase_order_approval_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    purchase_order_id BIGINT NOT NULL,

    approval_rule_id BIGINT,

    approval_level INTEGER NOT NULL DEFAULT 1,

    approver_id BIGINT,

    approval_source VARCHAR(20) NOT NULL DEFAULT 'USER',

    decision VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    po_total_at_decision NUMERIC(18,2) NOT NULL,

    comments TEXT,

    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    decided_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_po_approvals_order
        FOREIGN KEY (purchase_order_id)
        REFERENCES purchase_orders (purchase_order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_po_approvals_rule
        FOREIGN KEY (approval_rule_id)
        REFERENCES approval_rules (approval_rule_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_po_approvals_approver
        FOREIGN KEY (approver_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_po_approvals_level
        CHECK (approval_level > 0),

    CONSTRAINT chk_po_approvals_source
        CHECK (
            approval_source IN (
                'SYSTEM',
                'USER'
            )
        ),

    CONSTRAINT chk_po_approvals_decision
        CHECK (
            decision IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'RETURNED_FOR_AMENDMENT',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_po_approvals_total
        CHECK (po_total_at_decision >= 0),

    CONSTRAINT chk_po_approvals_approver_source
        CHECK (
            (
                approval_source = 'SYSTEM'
                AND approver_id IS NULL
            )
            OR
            (
                approval_source = 'USER'
                AND approver_id IS NOT NULL
            )
        ),

    CONSTRAINT chk_po_approvals_comments
        CHECK (
            decision NOT IN (
                'REJECTED',
                'RETURNED_FOR_AMENDMENT'
            )
            OR NULLIF(BTRIM(comments), '') IS NOT NULL
        ),

    CONSTRAINT chk_po_approvals_decided_at
        CHECK (
            (decision = 'PENDING' AND decided_at IS NULL)
            OR
            (decision <> 'PENDING' AND decided_at IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_po_approvals_order
    ON purchase_order_approvals (purchase_order_id);

CREATE INDEX IF NOT EXISTS idx_po_approvals_approver
    ON purchase_order_approvals (approver_id);

CREATE INDEX IF NOT EXISTS idx_po_approvals_decision
    ON purchase_order_approvals (decision);

CREATE INDEX IF NOT EXISTS idx_po_approvals_source
    ON purchase_order_approvals (approval_source);

CREATE INDEX IF NOT EXISTS idx_po_approvals_level
    ON purchase_order_approvals (
        purchase_order_id,
        approval_level
    );

CREATE UNIQUE INDEX IF NOT EXISTS uq_po_approvals_pending_level
    ON purchase_order_approvals (
        purchase_order_id,
        approval_level
    )
    WHERE decision = 'PENDING';


-- =========================================================
-- PURCHASE REQUISITION STATUS HISTORY
-- =========================================================

CREATE TABLE IF NOT EXISTS purchase_requisition_status_history (
    purchase_requisition_status_history_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    purchase_requisition_id BIGINT NOT NULL,

    previous_status VARCHAR(30),

    new_status VARCHAR(30) NOT NULL,

    action VARCHAR(50) NOT NULL,

    comments TEXT,

    changed_by BIGINT,

    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pr_status_history_requisition
        FOREIGN KEY (purchase_requisition_id)
        REFERENCES purchase_requisitions (purchase_requisition_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_pr_status_history_changed_by
        FOREIGN KEY (changed_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_pr_status_history_previous_status
        CHECK (
            previous_status IS NULL
            OR previous_status IN (
                'DRAFT',
                'SUBMITTED',
                'PENDING_APPROVAL',
                'RETURNED_FOR_AMENDMENT',
                'APPROVED',
                'REJECTED',
                'CANCELLED',
                'PARTIALLY_CONVERTED',
                'CONVERTED_TO_PO',
                'CLOSED'
            )
        ),

    CONSTRAINT chk_pr_status_history_new_status
        CHECK (
            new_status IN (
                'DRAFT',
                'SUBMITTED',
                'PENDING_APPROVAL',
                'RETURNED_FOR_AMENDMENT',
                'APPROVED',
                'REJECTED',
                'CANCELLED',
                'PARTIALLY_CONVERTED',
                'CONVERTED_TO_PO',
                'CLOSED'
            )
        ),

    CONSTRAINT chk_pr_status_history_comments
        CHECK (
            action NOT IN (
                'REJECT',
                'RETURN_FOR_AMENDMENT',
                'CANCEL'
            )
            OR NULLIF(BTRIM(comments), '') IS NOT NULL
        )
);

CREATE INDEX IF NOT EXISTS idx_pr_status_history_requisition
    ON purchase_requisition_status_history (purchase_requisition_id);

CREATE INDEX IF NOT EXISTS idx_pr_status_history_new_status
    ON purchase_requisition_status_history (new_status);

CREATE INDEX IF NOT EXISTS idx_pr_status_history_changed_by
    ON purchase_requisition_status_history (changed_by);

CREATE INDEX IF NOT EXISTS idx_pr_status_history_changed_at
    ON purchase_requisition_status_history (changed_at);


-- =========================================================
-- PURCHASE ORDER STATUS HISTORY
-- =========================================================

CREATE TABLE IF NOT EXISTS purchase_order_status_history (
    purchase_order_status_history_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    purchase_order_id BIGINT NOT NULL,

    revision_number INTEGER NOT NULL DEFAULT 0,

    previous_status VARCHAR(30),

    new_status VARCHAR(30) NOT NULL,

    action VARCHAR(50) NOT NULL,

    comments TEXT,

    changed_by BIGINT,

    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_po_status_history_order
        FOREIGN KEY (purchase_order_id)
        REFERENCES purchase_orders (purchase_order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_po_status_history_changed_by
        FOREIGN KEY (changed_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_po_status_history_revision
        CHECK (revision_number >= 0),

    CONSTRAINT chk_po_status_history_previous_status
        CHECK (
            previous_status IS NULL
            OR previous_status IN (
                'DRAFT',
                'SUBMITTED',
                'PENDING_APPROVAL',
                'RETURNED_FOR_AMENDMENT',
                'APPROVED',
                'REJECTED',
                'ON_HOLD',
                'CANCELLED',
                'SENT_TO_SUPPLIER',
                'PARTIALLY_RECEIVED',
                'FULLY_RECEIVED',
                'PARTIALLY_INVOICED',
                'FULLY_INVOICED',
                'MATCHING_EXCEPTION',
                'MATCHED',
                'CLOSED'
            )
        ),

    CONSTRAINT chk_po_status_history_new_status
        CHECK (
            new_status IN (
                'DRAFT',
                'SUBMITTED',
                'PENDING_APPROVAL',
                'RETURNED_FOR_AMENDMENT',
                'APPROVED',
                'REJECTED',
                'ON_HOLD',
                'CANCELLED',
                'SENT_TO_SUPPLIER',
                'PARTIALLY_RECEIVED',
                'FULLY_RECEIVED',
                'PARTIALLY_INVOICED',
                'FULLY_INVOICED',
                'MATCHING_EXCEPTION',
                'MATCHED',
                'CLOSED'
            )
        ),

    CONSTRAINT chk_po_status_history_comments
        CHECK (
            action NOT IN (
                'REJECT',
                'RETURN_FOR_AMENDMENT',
                'HOLD',
                'CANCEL'
            )
            OR NULLIF(BTRIM(comments), '') IS NOT NULL
        )
);

CREATE INDEX IF NOT EXISTS idx_po_status_history_order
    ON purchase_order_status_history (purchase_order_id);

CREATE INDEX IF NOT EXISTS idx_po_status_history_revision
    ON purchase_order_status_history (revision_number);

CREATE INDEX IF NOT EXISTS idx_po_status_history_new_status
    ON purchase_order_status_history (new_status);

CREATE INDEX IF NOT EXISTS idx_po_status_history_changed_by
    ON purchase_order_status_history (changed_by);

CREATE INDEX IF NOT EXISTS idx_po_status_history_changed_at
    ON purchase_order_status_history (changed_at);

CREATE INDEX IF NOT EXISTS idx_po_status_history_order_time
    ON purchase_order_status_history (
        purchase_order_id,
        changed_at
    );


-- =========================================================
-- NOTIFICATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    recipient_user_id BIGINT NOT NULL,

    notification_type VARCHAR(50) NOT NULL,

    title VARCHAR(200) NOT NULL,

    message TEXT NOT NULL,

    related_entity_type VARCHAR(50),

    related_entity_id BIGINT,

    delivery_channel VARCHAR(20) NOT NULL DEFAULT 'IN_APP',

    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    read_at TIMESTAMPTZ,

    sent_at TIMESTAMPTZ,

    failure_reason TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_recipient
        FOREIGN KEY (recipient_user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_notifications_channel
        CHECK (
            delivery_channel IN (
                'IN_APP',
                'EMAIL'
            )
        ),

    CONSTRAINT chk_notifications_status
        CHECK (
            status IN (
                'PENDING',
                'SENT',
                'FAILED',
                'READ'
            )
        ),

    CONSTRAINT chk_notifications_related_entity
        CHECK (
            (
                related_entity_type IS NULL
                AND related_entity_id IS NULL
            )
            OR
            (
                related_entity_type IS NOT NULL
                AND related_entity_id IS NOT NULL
            )
        ),

    CONSTRAINT chk_notifications_failure_reason
        CHECK (
            status <> 'FAILED'
            OR NULLIF(BTRIM(failure_reason), '') IS NOT NULL
        ),

    CONSTRAINT chk_notifications_read_at
        CHECK (
            status <> 'READ'
            OR read_at IS NOT NULL
        )
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient
    ON notifications (recipient_user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_status
    ON notifications (status);

CREATE INDEX IF NOT EXISTS idx_notifications_type
    ON notifications (notification_type);

CREATE INDEX IF NOT EXISTS idx_notifications_created_at
    ON notifications (created_at);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_status
    ON notifications (
        recipient_user_id,
        status
    );


-- =========================================================
-- AUDIT LOGS
-- =========================================================

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT,

    entity_type VARCHAR(50) NOT NULL,

    entity_id BIGINT NOT NULL,

    action VARCHAR(50) NOT NULL,

    previous_values JSONB,

    new_values JSONB,

    reason TEXT,

    request_id UUID,

    ip_address INET,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user
    ON audit_logs (user_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_type
    ON audit_logs (entity_type);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_id
    ON audit_logs (entity_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_action
    ON audit_logs (action);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
    ON audit_logs (created_at);

CREATE INDEX IF NOT EXISTS idx_audit_logs_request_id
    ON audit_logs (request_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_history
    ON audit_logs (
        entity_type,
        entity_id,
        created_at
    );

COMMIT;
