BEGIN;

CREATE SCHEMA IF NOT EXISTS procurement;

SET search_path TO procurement, public;

CREATE TABLE IF NOT EXISTS warehouses (
    warehouse_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    warehouse_code VARCHAR(30) NOT NULL,
    warehouse_name VARCHAR(150) NOT NULL,
    warehouse_type VARCHAR(30) NOT NULL,

    address VARCHAR(300),
    city VARCHAR(100),
    state VARCHAR(100),
    postcode VARCHAR(20),

    country VARCHAR(100) NOT NULL DEFAULT 'Australia',

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,

    CONSTRAINT uq_warehouses_warehouse_code
        UNIQUE (warehouse_code)
);

CREATE TABLE IF NOT EXISTS warehouse_locations (
    warehouse_location_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    warehouse_id BIGINT NOT NULL,

    location_code VARCHAR(40) NOT NULL,
    location_name VARCHAR(150) NOT NULL,
    location_type VARCHAR(30) NOT NULL,

    aisle VARCHAR(30),
    rack VARCHAR(30),
    bin VARCHAR(30),

    is_receiving_location BOOLEAN NOT NULL DEFAULT FALSE,
    is_quarantine_location BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,

    CONSTRAINT fk_warehouse_location_warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES warehouses (warehouse_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_warehouse_location_code
        UNIQUE (warehouse_id, location_code)
);

CREATE INDEX IF NOT EXISTS idx_warehouses_code
    ON warehouses (warehouse_code);

CREATE INDEX IF NOT EXISTS idx_warehouses_type
    ON warehouses (warehouse_type);

CREATE INDEX IF NOT EXISTS idx_warehouses_active
    ON warehouses (is_active);

CREATE INDEX IF NOT EXISTS idx_warehouse_locations_warehouse
    ON warehouse_locations (warehouse_id);

CREATE INDEX IF NOT EXISTS idx_warehouse_locations_type
    ON warehouse_locations (location_type);

CREATE INDEX IF NOT EXISTS idx_warehouse_locations_active
    ON warehouse_locations (is_active);

CREATE INDEX IF NOT EXISTS idx_warehouse_locations_receiving
    ON warehouse_locations (
        warehouse_id,
        is_receiving_location
    );

COMMIT;