BEGIN;
SET search_path TO procurement, public;

CREATE TABLE IF NOT EXISTS inventory_balances (
    inventory_balance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalogue_item_id BIGINT NOT NULL,
    unit_of_measure VARCHAR(30) NOT NULL,
    on_hand_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    available_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    quarantine_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    last_transaction_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_inventory_balance_item UNIQUE (catalogue_item_id),
    CONSTRAINT fk_inventory_balance_catalogue_item FOREIGN KEY (catalogue_item_id)
        REFERENCES catalogue_items (catalogue_item_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_inventory_balance_on_hand CHECK (on_hand_quantity >= 0),
    CONSTRAINT chk_inventory_balance_available CHECK (available_quantity >= 0),
    CONSTRAINT chk_inventory_balance_quarantine CHECK (quarantine_quantity >= 0)
);

CREATE TABLE IF NOT EXISTS inventory_transactions (
    inventory_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalogue_item_id BIGINT NOT NULL,
    transaction_type VARCHAR(30) NOT NULL,
    quantity NUMERIC(18,4) NOT NULL,
    unit_of_measure VARCHAR(30) NOT NULL,
    source_document_type VARCHAR(30) NOT NULL,
    source_document_id BIGINT NOT NULL,
    source_line_id BIGINT NOT NULL,
    reference_number VARCHAR(100),
    notes TEXT,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_transaction_catalogue_item FOREIGN KEY (catalogue_item_id)
        REFERENCES catalogue_items (catalogue_item_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_inventory_transaction_type CHECK (
        transaction_type IN ('RECEIPT','ADJUSTMENT_IN','ADJUSTMENT_OUT','ISSUE','RETURN')
    ),
    CONSTRAINT chk_inventory_transaction_quantity CHECK (quantity <> 0),
    CONSTRAINT uq_inventory_transaction_source_line UNIQUE (
        source_document_type, source_document_id, source_line_id, transaction_type
    )
);

CREATE INDEX IF NOT EXISTS idx_inventory_balance_item ON inventory_balances (catalogue_item_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transaction_item ON inventory_transactions (catalogue_item_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transaction_created ON inventory_transactions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_transaction_source ON inventory_transactions (source_document_type, source_document_id);

COMMIT;
